<?php

declare(strict_types=1);

$finder = (new PhpCsFixer\Finder())
    // bundles/ only exists once exercise 3 is solved.
    ->in(array_filter([__DIR__ . '/src', __DIR__ . '/tests', __DIR__ . '/config', __DIR__ . '/public', __DIR__ . '/bundles'], 'is_dir'))
    ->exclude(['var', 'vendor'])
    // Generated by Symfony on every dev cache warmup.
    ->notPath('reference.php')
    ->append([__FILE__]);

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(true)
    ->setCacheFile(__DIR__ . '/var/cache/.php-cs-fixer.cache')
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        '@PER-CS' => true,
        'declare_strict_types' => true,
        'native_function_invocation' => ['include' => ['@compiler_optimized'], 'scope' => 'namespaced', 'strict' => true],
        'phpdoc_to_comment' => false,
        'phpdoc_align' => false,
        // PropertyInfoTest reads the summary of a docblock: no added full stop.
        'phpdoc_summary' => false,
        'trailing_comma_in_multiline' => ['elements' => ['arrays', 'arguments', 'parameters']],
        'php_unit_test_class_requires_covers' => false,
        'php_unit_internal_class' => false,
    ])
    ->setFinder($finder);
